'variables':
  'rate':
    varsn   : 'RATE'
    varln   : 'Rain rate'
    units   : 'mm/h'
    livelli : [0.,1.,5.,10.,20.,50.,75.,100.,150.,200.,]
    colori  : ['#a4aab3','#3288bd','#66c2a5','#abdda4','#e6f598',
               '#fee08b','#fdae61','#f46d43','#d53e4f']
  'acrr':
    varsn   : 'ACRR'
    varln   : 'Radar Precipitation amount'
    units   : 'mm'
    #livelli = [0.,1.,5.,10.,20.,50.,75.,100.,150.,200.,]
    livelli : [0.,1,2,5,10,20,30,50,70,100,150,200,300,500]
    colori : ['#a4aab3','#f0f0f0','#d0d1e6','#a6bddb',
             '#74a9cf','#2b8cbe','#045a8d',
             '#fecc5c','#fd8d3c','#e31a1c',
             '#dd3497','#ae017e','#7a0177']
  'dbzh':
    varsn   : 'DBZH'
    varln   : 'radar reflectivity'
    units   : 'dBZ'
    livelli : [-31.,0.,1.,10.,20.,30.,40.,50.,60.,70.]
    colori  : ['#a4aab3','#3288bd','#66c2a5','#abdda4','#e6f598',
               '#fee08b','#fdae61','#f46d43','#d53e4f']